# Generated by Django 2.0.1 on 2023-10-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_remove_contact_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='marital_status',
            field=models.CharField(choices=[('', 'Single'), ('', 'Married'), ('', 'Divorced'), ('', 'Widowed')], default=2, max_length=7),
            preserve_default=False,
        ),
    ]
